/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sistema_contable_v.pkg1.CatalogoDeCuentas;

/**
 *
 * @author mateo
 */
public class Catalogo extends javax.swing.JFrame {
    CatalogoDeCuentas catalogo;
    DefaultTableModel modelo;
    DefaultComboBoxModel modeloCmb;
    Object culumnas[] = {"Codigo","Tipo","Nombre", "Tipo de Balance", "Descripción"};
    int accionGuardar = 0; //para verificar si se trata de Modificar o Agregar cuentas (1 para guardar y 2 para modificar)

    /**
     * Creates new form Catalogo
     */
    public Catalogo() {
        initComponents();
        setLocationRelativeTo(null);
        cuentas();
        tipos();
        controles(0);
    }
    
    public void cuentas() {
        catalogo = new CatalogoDeCuentas();
        
        Object datos[][] = catalogo.mostrarCuentas();
        modelo = new DefaultTableModel(datos, culumnas);
        tblCatalogo.setModel(modelo);
        
        int anchos[] = {20,20,200,100,400};
        for (int i = 0; i < tblCatalogo.getColumnCount() ;i++) {
            tblCatalogo.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
            
        }
    }
    
    public void tipos(){
        catalogo = new CatalogoDeCuentas();
        
        Object tipo[] = catalogo.tiposCuenta();
        modeloCmb = new DefaultComboBoxModel(tipo);
        cmbTipo.setModel(modeloCmb);
    }
    
    public void limpiarFormulario(){
        //Limpiamos el formulario
        cmbTipo.setSelectedIndex(0);
        txtCodigo.setText("");
        txtNombre.setText("");
        cmbBalance.setSelectedIndex(0);
        txtDescripcion.setText("");
        
        //Bloquamos Algunos controles
        controles(0);
        
    }
    
    public void controles(int accion){
        switch(accion){
            //Si la accion es 0 bloquamos los controles
            case 0:
                btnAgregar.setEnabled(true);
                btnModificar.setEnabled(true);
                btnEliminar.setEnabled(true);
                btnGuardar.setEnabled(false);
                btnCancelar.setEnabled(false);
                
                cmbTipo.setEnabled(false);
                txtCodigo.setEnabled(false);
                txtNombre.setEnabled(false);
                cmbBalance.setEnabled(false);
                txtDescripcion.setEnabled(false);
                break;
            //Si la accion es 1 desbloquamos los controles
            case 1:
                btnAgregar.setEnabled(false);
                btnModificar.setEnabled(false);
                btnEliminar.setEnabled(false);
                btnGuardar.setEnabled(true);
                btnCancelar.setEnabled(true);
                
                cmbTipo.setEnabled(true);
                txtCodigo.setEnabled(true);
                txtNombre.setEnabled(true);
                cmbBalance.setEnabled(true);
                txtDescripcion.setEnabled(true);
        }
    }
    
    public boolean validar(){
        int codTipo = cmbTipo.getSelectedIndex();
        int codBalance = cmbBalance.getSelectedIndex();
        
        return (codTipo != 0) & (codBalance != 0) & (!txtCodigo.getText().equals("")) & (!txtNombre.getText().equals("")) & (!txtDescripcion.getText().equals(""));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblCatalogo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        cmbBalance = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        btnEliminar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 560));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblCatalogo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblCatalogo);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 37, 976, 299));

        jLabel1.setText("Tipo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 354, -1, -1));

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 150, -1));

        jLabel2.setText("Codigo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, -1, -1));

        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 381, 100, -1));

        jLabel3.setText("Nombre");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 360, -1, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 381, 300, -1));

        cmbBalance.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Selección---", "Normal", "Ajuste" }));
        getContentPane().add(cmbBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 380, 180, -1));

        jLabel4.setText("Tipo Balance");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(616, 354, -1, -1));

        jLabel5.setText("Descripción");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 436, -1, -1));

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 418, 386, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 470, 130, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(666, 441, 130, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 441, 130, -1));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 420, 130, -1));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 370, 130, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/fondo_menu.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
         int fila;
        
        if (tblCatalogo.getSelectedRow() > -1) {
            fila = tblCatalogo.getSelectedRow();
            
            //Preparamos el formulario
            
            //obtenemos el tipo de cuenta
            int tipoCuenta = 0;
            switch(tblCatalogo.getValueAt(fila, 1).toString()){
                case "Activo":
                    tipoCuenta = 1;
                    break;
                case "Pasivo":
                    tipoCuenta = 2;
                    break;
                case "Capital":
                    tipoCuenta = 3;
                    break;
            }
            
            //obtenemos el tipo de balance
            int tipoBalance = 0;
            switch(tblCatalogo.getValueAt(fila, 3).toString()){
                case "Normal":
                    tipoBalance = 1;
                    break;
                case "Ajuste":
                    tipoBalance = 2;
                    break;
            }
            
            cmbTipo.setSelectedIndex(tipoCuenta);
            txtCodigo.setText(tblCatalogo.getValueAt(fila, 0).toString());
            txtNombre.setText(tblCatalogo.getValueAt(fila, 2).toString());
            cmbBalance.setSelectedIndex(tipoBalance);
            txtDescripcion.setText(tblCatalogo.getValueAt(fila, 4).toString());
            
            //habilitamos los controles necesarios y establecemos la accion de modificar
            controles(1);
            cmbTipo.setEnabled(false);
            txtCodigo.setEnabled(false);
            accionGuardar = 2;
            
        }else{
            JOptionPane.showMessageDialog(null, "No se ha seleccionado Ninguna cuenta");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
         controles(1);
         accionGuardar = 1;
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila;
        
        if (tblCatalogo.getSelectedRow() > -1) {
            fila = tblCatalogo.getSelectedRow();
            
            int codigo = Integer.parseInt(String.valueOf(tblCatalogo.getValueAt(fila, 0)));
            
            catalogo = new CatalogoDeCuentas();
            catalogo.eliminarCuenta(codigo);
            
            //actualizamos el contenido de la tabla
            cuentas();
            
        }else{
            JOptionPane.showMessageDialog(null, "No se ha seleccionado Ninguna cuenta");
        }
         
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if(validar()) {
            int tipo = cmbTipo.getSelectedIndex();
            int codigo = Integer.parseInt(txtCodigo.getText());
            String nombre = txtNombre.getText();
            String descripcion = txtDescripcion.getText();
            int balance = cmbBalance.getSelectedIndex();

            if(accionGuardar==1){
                catalogo = new CatalogoDeCuentas(codigo, tipo, nombre, balance, descripcion);
                catalogo.agregarCuenta();

                JOptionPane.showMessageDialog(null, "La cuenta se ha registrado exitosamente", "Registro", 1);
            }else{
                catalogo = new CatalogoDeCuentas();
                catalogo.modificarCuenta(codigo, nombre, balance, descripcion);

                JOptionPane.showMessageDialog(null, "La cuenta se ha modificado exitosamente", "Modificación", 1);
            }
            
            limpiarFormulario();
            cuentas();
        }else{
            JOptionPane.showMessageDialog(null, "Por favor complete el formulario", "Error", 1);
        }
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiarFormulario();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
        char car = evt.getKeyChar();
        if(Character.isLetter(car)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtCodigoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Catalogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cmbBalance;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblCatalogo;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
