/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sistema_contable_v.pkg1.CatalogoDeCuentas;
import sistema_contable_v.pkg1.LibroDiario;

/**
 *
 * @author mateo
 */
public class Diario extends javax.swing.JFrame {
    DefaultTableModel modeloDiario;
    Object culumnas[] = {"Cuenta","Cargo","Abono"};
    LibroDiario diario;
    double cargo = 0;
    double abono = 0;

    /**
     * Creates new form LibroDiario
     */
    public Diario() {
        initComponents();
        setLocationRelativeTo(null);
        cargarDatos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDiario = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();
        lblAbono = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtPartida = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCuenta = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCargo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtAbono = new javax.swing.JTextField();
        btnAgregarMovimiento = new javax.swing.JButton();
        btnEliminarMovimiento = new javax.swing.JButton();
        btnGuardarPartida = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDiario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Cuenta", "Cargo", "Abono"
            }
        ));
        jScrollPane1.setViewportView(tblDiario);
        if (tblDiario.getColumnModel().getColumnCount() > 0) {
            tblDiario.getColumnModel().getColumn(0).setResizable(false);
            tblDiario.getColumnModel().getColumn(1).setResizable(false);
            tblDiario.getColumnModel().getColumn(2).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 224, 857, 111));

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane2.setViewportView(txtDescripcion);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 353, 301, -1));

        jLabel3.setText("Concepto:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 353, -1, -1));

        jLabel4.setText(" Total");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel4.setPreferredSize(new java.awt.Dimension(100, 17));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 353, -1, -1));

        lblCargo.setText(" $0.0");
        lblCargo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblCargo.setPreferredSize(new java.awt.Dimension(100, 17));
        getContentPane().add(lblCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 353, -1, -1));

        lblAbono.setText(" 0.0");
        lblAbono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblAbono.setPreferredSize(new java.awt.Dimension(100, 17));
        getContentPane().add(lblAbono, new org.netbeans.lib.awtextra.AbsoluteConstraints(701, 353, -1, -1));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel2.setText("Fecha:");

        txtFecha.setEnabled(false);

        jLabel1.setText("Número de partida");

        txtPartida.setEnabled(false);

        jLabel7.setText("Codigo");

        txtCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodigoFocusLost(evt);
            }
        });

        jLabel8.setText("Cuenta");

        txtCuenta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCuentaFocusLost(evt);
            }
        });

        jLabel9.setText("Cargo");

        txtCargo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCargoFocusGained(evt);
            }
        });
        txtCargo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCargoKeyTyped(evt);
            }
        });

        jLabel10.setText("Abono");

        txtAbono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAbonoFocusGained(evt);
            }
        });
        txtAbono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAbonoKeyTyped(evt);
            }
        });

        btnAgregarMovimiento.setText("Agregar movimiento");
        btnAgregarMovimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarMovimientoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(12, 12, 12)
                        .addComponent(txtPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel2)
                        .addGap(12, 12, 12)
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(txtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtAbono, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(btnAgregarMovimiento)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAbono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarMovimiento))
                .addGap(38, 38, 38))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 38, -1, -1));

        btnEliminarMovimiento.setText("Eliminar Movimiento");
        btnEliminarMovimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarMovimientoActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarMovimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 406, -1, -1));

        btnGuardarPartida.setText("Guardar Partida");
        btnGuardarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPartidaActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardarPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 406, 175, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/fondo_menu.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoFocusLost
        if(!txtCodigo.getText().equals("")){
            diario = new LibroDiario();
            
            String nombre = diario.buscar("cuenta", txtCodigo.getText());
            
            if(!nombre.equals("")){
                txtCuenta.setText(nombre);
            }else{
                JOptionPane.showMessageDialog(null,"El codigo de la cuenta no existe");
            }
        }
    }//GEN-LAST:event_txtCodigoFocusLost

    private void txtCuentaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCuentaFocusLost
        if(!txtCuenta.getText().equals("")){
            diario = new LibroDiario();
            
            String codigo = diario.buscar("codigo", txtCuenta.getText());
            
            if(!codigo.equals("")){
                txtCodigo.setText(codigo);
            }else{
                JOptionPane.showMessageDialog(null,"El nombre de la cuenta no existe");
            }
        }
    }//GEN-LAST:event_txtCuentaFocusLost

    private void txtCargoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCargoKeyTyped
        char car = evt.getKeyChar();
        if(Character.isLetter(car)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtCargoKeyTyped

    private void txtAbonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAbonoKeyTyped
        char car = evt.getKeyChar();
        if(Character.isLetter(car)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtAbonoKeyTyped

    private void btnAgregarMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMovimientoActionPerformed
        if(validarPartida()){
            if(!txtCargo.getText().equals("")){
                cargo = cargo + Double.parseDouble(txtCargo.getText());
            }
            if(!txtAbono.getText().equals("")){
                abono = abono + Double.parseDouble(txtAbono.getText());
            }        
            Object[] asientoDiario = {txtCuenta.getText(), txtCargo.getText(), txtAbono.getText()};

            modeloDiario.addRow(asientoDiario);
            lblCargo.setText(" $"+cargo);
            lblAbono.setText(" $"+abono);

            limpiarFormulario();
        }
    }//GEN-LAST:event_btnAgregarMovimientoActionPerformed

    private void txtCargoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCargoFocusGained
        txtAbono.setText("");
    }//GEN-LAST:event_txtCargoFocusGained

    private void txtAbonoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAbonoFocusGained
        txtCargo.setText("");
    }//GEN-LAST:event_txtAbonoFocusGained

    private void btnEliminarMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarMovimientoActionPerformed
        int fila;
        
        if (tblDiario.getSelectedRow() > -1) {
            fila = tblDiario.getSelectedRow();
            
            if(!tblDiario.getValueAt(fila, 1).equals("")){
                cargo = cargo - Double.parseDouble(String.valueOf(tblDiario.getValueAt(fila, 1)));
            }
            if(!tblDiario.getValueAt(fila, 2).equals("")){
                abono = abono - Double.parseDouble(String.valueOf(tblDiario.getValueAt(fila, 2)));
            }
 
            lblCargo.setText(" $"+cargo);
            lblAbono.setText(" $"+abono);
            
            modeloDiario.removeRow(fila);
        }else{
            JOptionPane.showMessageDialog(null, "No se ha seleccionado Ninguna cuenta");
        }
    }//GEN-LAST:event_btnEliminarMovimientoActionPerformed

    private void btnGuardarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPartidaActionPerformed
        int numRegistros = tblDiario.getRowCount();
        if(numRegistros >= 2){
            if(cargo == abono){
               int partida = Integer.parseInt(txtPartida.getText());
               String fecha = txtFecha.getText();
               String concepto = txtDescripcion.getText();
               int[] codigo = new int[numRegistros];
               double[] cargos = new double[numRegistros];
               double[] abonos = new double[numRegistros];
                for (int i = 0; i < numRegistros; i++) {
                    diario = new LibroDiario();

                    codigo[i] = Integer.parseInt(diario.buscar("codigo", String.valueOf(tblDiario.getValueAt(i, 0))));
                    if(!tblDiario.getValueAt(i, 1).equals("")){
                        cargos[i] = Double.parseDouble(String.valueOf(tblDiario.getValueAt(i, 1)));
                        abonos[i] = 0;
                    }else{
                        abonos[i] = Double.parseDouble(String.valueOf(tblDiario.getValueAt(i, 2)));
                        cargos[i] = 0;
                    }
                }
                 
                diario = new LibroDiario(partida, fecha, codigo, cargos, abonos, concepto);
                diario.registarPartida();
                
                cargarDatos();
                limpiarFormulario();
            }else{
                JOptionPane.showMessageDialog(null, "Los totales de cargo y abono no coinciden");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Debe de realizar almenos dos movimientos para guardar la partida");
        }
    }//GEN-LAST:event_btnGuardarPartidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Diario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Diario().setVisible(true);
            }
        });
    }
    
    private void cargarDatos(){
        //Inicializa la tabla
        modeloDiario = new DefaultTableModel(culumnas, 0);
        tblDiario.setModel(modeloDiario);
        
        int anchos[] = {400,20,20};
        for (int i = 0; i < tblDiario.getColumnCount() ;i++) {
            tblDiario.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
            
        }
        
        //Genera el numero de partida
        diario = new LibroDiario();
        txtPartida.setText(String.valueOf(diario.obtenerPartida()));
        
        //Genera la fecha actual
        Date fecha = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        
        txtFecha.setText(formato.format(fecha));
    }
    
    private void limpiarFormulario(){
        txtCodigo.setText("");
        txtCuenta.setText("");
        txtCargo.setText("");
        txtAbono.setText("");
        txtDescripcion.setText("");
    }
    
    private boolean validarPartida(){
        boolean validar= false;
        if(!txtCodigo.getText().equals("") && (!txtCargo.getText().equals("") || !txtAbono.getText().equals(""))){
            validar = true;
        }
        return validar;
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarMovimiento;
    private javax.swing.JButton btnEliminarMovimiento;
    private javax.swing.JButton btnGuardarPartida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAbono;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JTable tblDiario;
    private javax.swing.JTextField txtAbono;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCuenta;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtPartida;
    // End of variables declaration//GEN-END:variables
}
